### ISSUE TITLE
Tweaks & fixes

### ISSUE THREAD

**Issue by psolymos** [psolymos/moosecounter#21]
### 1. Crosstalk-like behaviour for univariate plots

> In the “Univariate Graph” tab – would it be possible to highlight a point on one of the graphs and see where it is in the other 2? So for example, if I click or scroll over a point in the scatter plot on the right, would it possible to see where that point is on the middle graph in the map?

Use plotly::event_data()  or crosstalk?

### 2. Histogram binning

> For the histogram predicting the total population, would it possible to specify the number of bins? Sometimes the graph is very ugly

### 3. Total Prediction map/summary subsets

> For the Total Prediction, if the data are subset then the Map and the Summary show only the subset data but the plot keeps all the data. Could we change it so the plot also has only the subset data?

### 4. Export data: check if it is all or subset

> I would have to go back and double check but I also think that when we are working with a subset of data and you get to the end looking at predictions, if you download the excel table you end up getting the complete dataset.

### 5. Plotly image download issues

> There is one issue that we actually really need fixed and it sounds like it’s a Mac/Windows issue. We are not able to use the download tool for all the graphs and plots (in the Total and Composition tabs) so the only thing we can do is screenshot. Ideally, it would be great to download (or even copy/paste) individual graphs/plots.

- Test download functionality in Chrome/Firefox/Safari (Mac) and Chrome/Firefox/Safari/Edge on Windows
- Likely need to add download button using plotly::export()  https://github.com/plotly/plotly.R/issues/672

## TODO list

- [x] 1. Crosstalk-like behaviour for univariate plots
- [x] 2. Histogram binning
- [x] 3. Total Prediction map/summary subsets
- [x] 4. Export data: check if it is all or subset
- [x] 5. Plotly image download issues

**Comment by steffilazerte** [comment]
Just one clarification: For the export data when there is a subset (4), do we want to (a) export only the subset, or (b) offer a choice to the user?

**Comment by psolymos** [comment]
> Just one clarification: For the export data when there is a subset (4), do we want to (a) export only the subset, or (b) offer a choice to the user?

I think either only the subset, or have 2 export buttons, one for the entire data and one for the subset (which by default is the entire data without filters being added). This would avoid confusion and would help getting the full data even through a subset has been selected.

**Comment by steffilazerte** [comment]
Okay, I think I've address everything here (except the image downloading). Let me know if you find anything that needs tweaking!
